version: 2.1
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: testing building Circle CI
          webhook: https://hooks.slack.com/services/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
orbs:
  slack: circleci/slack@x.y.z
workflows:
  your-workflow:
    jobs:
      - build
