version: 2
jobs:
  build:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "Building docker"
  test:
    docker:
      - image: ubuntu:18.04
    steps:
      - checkout
      - run: echo "Testing docker"
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
